version: "3.7"
services:
  db:
    image: mongo:4
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - 27018:27017

  app:
    image: siga-tracker
    container_name: siga-tracker-prod
    build:
      dockerfile: prod.dockerfile
      context: .
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app:cached
      - npm_cache:/root/.npm:delegated
      - node_modules:/app/node_modules:delegated
    environment:
      - MONGO_URI=${MONGO_URI}
      - USER=${USER}
      - PASS=${PASS}
    links:
      - db

volumes:
  npm_cache:
  node_modules:
  mongodb:
