version: "3.7"
services:
  db:
    image: mongo:4
    container_name: siga-tracker-db
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - 27018:27017

  app:
    image: docker.pkg.github.com/nicomigueles/siga-tracker/siga-tracker:latest
    container_name: siga-tracker-deamon
    restart: on-failure
    depends_on:
      - db
    environment:
      - MONGO_URI=${MONGO_URI}
      - USER=${USER}
      - PASS=${PASS}
    links:
      - db

volumes:
  mongodb:
