version: "3.7"
services:
  db:
    image: mongo:4
    restart: always
    volumes:
      - ./docker-data/db:/data/db
    ports:
      - 27018:27017

  app:
    image: siga-tracker
    build:
      dockerfile: dev.dockerfile
      context: .
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - npm_cache:/root/.npm:delegated
      - node_modules:/app/node_modules:delegated
    environment:
      - MONGO_URI=${MONGO_URI}
      - USER=${USER}
      - PASS=${PASS}
      - WEBHOOK_URL_NEW_COURSE=${WEBHOOK_URL_NEW_COURSE}
      - WEBHOOK_URL_NEW_GRADE=${WEBHOOK_URL_NEW_GRADE}
      - WEBHOOK_DISCORD=${WEBHOOK_DISCORD}
    links:
      - db

volumes:
  npm_cache:
  node_modules:
